{{- if or (eq .Values.deployment.kind "Deployment") (eq .Values.deployment.kind "StatefulSet") }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "common.names.fullname" . }}
  {{- include "app.metadata.template" . | nindent 2 }}
  {{- if .Values.service.annotations }}
  annotations:
    {{- include "common.tplvalues.render" ( dict "value" .Values.service.annotations "context" $) | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP}}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      name: {{ .name }}
      {{- if and (eq $.Values.service.type "NodePort") .nodePort}}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  selector:
    {{- include "common.labels.matchLabels" . | nindent 4 }}
{{- end -}}
